# Site settings
title: It will be soon
description: Blog of Shiqi Yao
baseurl: "" 
url: "https://shiqiyao941031.github.io" 

# GitHub User settings
username: Shiqi Yao
github_username: ShiqiYao941031
user_description: A new to GIS
user_title: student in GIS
email: shiqi_yao@outlook.com

# Blog Author settings
author:
  name:           Shiqi Yao
  picture:        
  email:          shiqi_yao@outlook.com
  description:    A new to GIS
  twitter:
  facebook:
  github:         https://github.com/ShiqiYao941031
  linkedin:


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  

permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"